font_size 13.0
font_family MesloLGS Nerd Font Mono
scrollback_lines 10000
hide_window_decorations titlebar-only

background_opacity 0.8
background_blur 8

# top, right, bottom and left.
window_padding_width 5 8 5 8 
