set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # Saves session every 15 minutes
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

# theme
set -g @theme_disable_plugins 1
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_transparent_status_bar 'true'
set -g @theme_transparent_left_separator_inverse ''
set -g @theme_transparent_right_separator_inverse ''
set -g status-position bottom

set -g prefix C-b

# panes
bind -r k resize-pane -U 10
bind -r j resize-pane -D 10
bind -r h resize-pane -L 10
bind -r l resize-pane -R 10

# utils
bind o run-shell "tmux capture-pane -S - -p > /tmp/tmux_buffer_tmp && tmux split-window 'nvim /tmp/tmux_buffer_tmp'"

# scrolling
bind -T copy-mode u send -X halfpage-up
bind -T copy-mode d send -X halfpage-down

unbind r
bind r source-file ~/dotfiles/.config/tmux/tmux.conf \; display-message "Config reloaded"

# mouse
set -g mouse on

# shell
set -g default-shell /bin/zsh
set -g default-command "zsh -l"

run -b '~/.tmux/plugins/tpm/tpm'
