after-login-command = []
after-startup-command = ['exec-and-forget sketchybar', 'workspace B']

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center']

accordion-padding = 20

[gaps]
inner.horizontal = 3
inner.vertical =   3
outer.left =       3
outer.bottom =     3
outer.top =        [{ monitor."^dell|HP E27d G4$" = 45 }, 5]
outer.right =      3

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

ctrl-shift-h = 'focus left'
ctrl-shift-j = 'focus down'
ctrl-shift-k = 'focus up'
ctrl-shift-l = 'focus right'

ctrl-alt-h = 'move left'
ctrl-alt-j = 'move down'
ctrl-alt-k = 'move up'
ctrl-alt-l = 'move right'

ctrl-alt-cmd-shift-y = 'resize smart -50'
ctrl-alt-cmd-shift-u = 'resize smart +50'
ctrl-alt-cmd-shift-f = 'fullscreen'
ctrl-alt-enter = 'fullscreen'

ctrl-alt-cmd-b = 'workspace B' # Browser
ctrl-alt-cmd-t = 'workspace T' # Terminal
ctrl-alt-cmd-m = 'workspace M' # Music
ctrl-alt-cmd-w = 'workspace W' # Main Monitor
ctrl-alt-cmd-s = 'workspace S' # Second Monitor
ctrl-alt-cmd-e = 'workspace E' # Third Monitor

ctrl-alt-cmd-shift-b = 'move-node-to-workspace B'
ctrl-alt-cmd-shift-t = 'move-node-to-workspace T'
ctrl-alt-cmd-shift-m = 'move-node-to-workspace M'
ctrl-alt-cmd-shift-w = 'move-node-to-workspace W'
ctrl-alt-cmd-shift-s = 'move-node-to-workspace S'
ctrl-alt-cmd-shift-e = 'move-node-to-workspace E'

# alt-tab = 'workspace-back-and-forth'
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-tab = 'workspace-back-and-forth'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main'] 
s = ['exec-and-forget brew services restart sketchybar', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-name-regex-substring = 'Citrix Workspace'
run = ['layout floating', 'move-node-to-workspace W']

[[on-window-detected]]
if.app-name-regex-substring = 'Citrix Viewer'
run = 'move-node-to-workspace W'

[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = ['layout floating', 'move-node-to-workspace T']

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = ['layout floating', 'move-node-to-workspace T']

[[on-window-detected]]
if.app-name-regex-substring = 'Finder|Passwords|Preview|Photos|FaceTime|Notes|QuickTime Player|Wireguard|Moonlight|Electron|Microsoft Remote Desktop|Obsidian'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp|Telegram|Discord'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'Karabiner|Vial'
run = ['layout floating']

[workspace-to-monitor-force-assignment]
S = ['HP E27d G4', 'DELL U3419W', 'secondary']
E = ['HP E27q G4']
