#!/usr/bin/env bash

HOME_DIR=${HOME}

mkdir -p ${HOME_DIR}/.config/{nvim,tmux,bat,kitty,karabiner,opencode}
mkdir -p ${HOME_DIR}/.config/opencode/agents

ln -s ${HOME_DIR}/dotfiles/.zshrc ${HOME_DIR}/.zshrc
ln -s ${HOME_DIR}/dotfiles/.gitconfig ${HOME_DIR}/.gitconfig
ln -s ${HOME_DIR}/dotfiles/.config/nvim ${HOME_DIR}/.config/nvim
ln -s ${HOME_DIR}/dotfiles/.config/tmux ${HOME_DIR}/.config/tmux
ln -s ${HOME_DIR}/dotfiles/.config/aerospace/aerospace.toml ${HOME_DIR}/.aerospace.toml
ln -s ${HOME_DIR}/dotfiles/.config/bat ${HOME_DIR}/.config/bat
ln -s ${HOME_DIR}/dotfiles/.config/kitty ${HOME_DIR}/.config/kitty
ln -s ${HOME_DIR}/dotfiles/.config/karabiner ${HOME_DIR}/.config/karabiner
ln -s ${HOME_DIR}/dotfiles/.config/agents ${HOME_DIR}/.agents
ln -s ${HOME_DIR}/dotfiles/.config/opencode/agents ${HOME_DIR}/.config/opencode/agents
ln -s ${HOME_DIR}/dotfiles/.config/opencode/opencode.json ${HOME_DIR}/.config/opencode/opencode.json
