#!/usr/bin/env bash

ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.config/nvim ~/.config/nvim
ln -s ~/dotfiles/.config/tmux ~/.config/tmux
ln -s ~/dotfiles/.config/aerospace/aerospace.toml ~/.aerospace.toml
ln -s ~/dotfiles/.config/bat ~/.config/bat
ln -s ~/dotfiles/.config/kitty ~/.config/kitty
ln -s ~/dotfiles/.config/karabiner ~/.config/karabiner
ln -s ~/dotfiles/.config/agents ~/.agents
ln -s ~/dotfiles/.config/opencode/agents ~/.config/opencode/agents
ln -s ~/dotfiles/.config/opencode/opencode.json ~/.config/opencode/opencode.json
