#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="SF Pro"
PADDING=3

# # Start CPU helper
# HELPER=git.sketchybar.helper
# killall helper
# cd $HOME/.config/sketchybar/helper && make
# $HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

bar=(
  height=39
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=3
  margin=10
  blur_radius=20
  notch_width=0
)
sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Bold:12.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  padding_right=$PADDING
  padding_left=$PADDING
  background.height=30
  background.corner_radius=9
  popup.background.border_width=1
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${default[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/separator.sh" "stats_separator" "right"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/network.sh"

sketchybar --hotload on
sketchybar --update
